insert into vehicles (name, year, color, brand_id) values ('Silverado 3500', 2007, 'Green', 8);
insert into vehicles (name, year, color, brand_id) values ('Mazdaspeed 3', 2008, 'Indigo', 1);
insert into vehicles (name, year, color, brand_id) values ('TL', 1996, 'Pink', 4);
insert into vehicles (name, year, color, brand_id) values ('Santa Fe', 2010, 'Mauv', 6);
insert into vehicles (name, year, color, brand_id) values ('Maxima', 2012, 'Violet', 3);
insert into vehicles (name, year, color, brand_id) values ('G3', 2010, 'Green', 3);
insert into vehicles (name, year, color, brand_id) values ('Sunbird', 1988, 'Fuscia', 6);
insert into vehicles (name, year, color, brand_id) values ('Pathfinder', 1992, 'Crimson', 3);
insert into vehicles (name, year, color, brand_id) values ('S6', 2009, 'Pink', 5);
insert into vehicles (name, year, color, brand_id) values ('GLI', 2008, 'Aquamarine', 8);
insert into vehicles (name, year, color, brand_id) values ('Sonoma', 1995, 'Fuscia', 2);
insert into vehicles (name, year, color, brand_id) values ('G-Series G20', 1992, 'Turquoise', 2);
insert into vehicles (name, year, color, brand_id) values ('Rodeo', 2004, 'Teal', 4);
insert into vehicles (name, year, color, brand_id) values ('8 Series', 1993, 'Mauv', 7);
insert into vehicles (name, year, color, brand_id) values ('Yukon XL 1500', 2004, 'Turquoise', 6);
insert into vehicles (name, year, color, brand_id) values ('Acclaim', 1993, 'Turquoise', 3);
insert into vehicles (name, year, color, brand_id) values ('LeMans', 1989, 'Pink', 4);
insert into vehicles (name, year, color, brand_id) values ('xB', 2005, 'Green', 3);
insert into vehicles (name, year, color, brand_id) values ('Caravan', 2001, 'Purple', 1);
insert into vehicles (name, year, color, brand_id) values ('SL-Class', 1990, 'Indigo', 6);